# Generated by Django 4.2.9 on 2024-02-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_remove_personfilmwork_film_work_person_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
    ]
