# Generated by Django 4.2.9 on 2024-05-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('movies', '0005_profile'), ('movies', '0006_remove_profile_uuid_alter_profile_id'), ('movies', '0007_rename_id_profile_uuid'), ('movies', '0008_alter_profile_uuid'), ('movies', '0009_alter_profile_user'), ('movies', '0010_profile_id_alter_profile_uuid'), ('movies', '0011_alter_profile_uuid')]

    dependencies = [
        ('movies', '0004_alter_genre_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
