# Generated by Django 4.2.9 on 2024-05-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_profile_squashed_0011_alter_profile_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
