# Для локальной разработки
version: "3.9"

services:

  # Common services

  movies-postgres:
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  # Movies API

  movies-api:
    ports:
      - "8000:8000"

  movies-redis:
    ports:
      - "6379:6379"

  # Movies Admin

  movies-admin:
    ports:
      - "8001:8000"

  # Auth

  auth-api:
    ports:
      - "8002:8000"

  auth-redis:
    ports:
      - "6380:6379"

  auth-postgres:
    ports:
      - "5433:5432"

  # Monitoring

  kibana:
    image: kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    profiles:
      - monitoring
