version: '3.8'
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env.prod
    deploy:
      restart_policy:
        condition: always

  redis:
    image: redis:alpine
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
  
  auth-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - redis
    env_file:
      - ./.env.prod
