# Generated by Django 4.2.9 on 2024-05-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_filmworkpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmworkpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userpermission'),
        ),
    ]
